# Generated by Django 4.2.4 on 2023-08-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm_global', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noc_Global_Choices',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fam_cad_cli',
            field=models.ForeignKey(db_comment='Família Cadastral do Cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tm_global.familiacadastral', verbose_name='Família Cadastral'),
        ),
    ]
