# Generated by Django 4.2.4 on 2023-08-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm_global', '0002_delete_noc_global_choices_alter_clientes_fam_cad_cli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fam_cad_cli',
            field=models.ForeignKey(blank=True, db_comment='Família Cadastral do Cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tm_global.familiacadastral', verbose_name='Família Cadastral'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='fam_cad_for',
            field=models.ForeignKey(blank=True, db_comment='Familia Cadastral do Fornecedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tm_global.familiacadastral', verbose_name='Família Cadastral'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='fam_cad_prod',
            field=models.ForeignKey(blank=True, db_comment='Família Cadastral do Produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tm_global.familiacadastral', verbose_name='Família Cadastral'),
        ),
    ]
