# Generated by Django 4.2.4 on 2023-08-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_global', '0003_alter_clientes_fam_cad_cli_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='lim_cred_cli',
            field=models.DecimalField(blank=True, db_comment='Limite de Crédito do Cliente', decimal_places=2, max_digits=8, null=True, verbose_name='Limite de Crédito'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='venc_lim_cred_cli',
            field=models.DateField(blank=True, db_comment='Data de Vencimento do Limite de Crédito do Cliente', null=True, verbose_name='Vencto.Lim.Créd.'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='lim_cred_for',
            field=models.DecimalField(blank=True, db_comment='Limite de Crédito do Fornecedor', decimal_places=2, max_digits=8, null=True, verbose_name='Limite de Crédito'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='venc_lim_cred_for',
            field=models.DateField(blank=True, db_comment='Data de Vencimento do Limite de Crédito do Fornecedor', null=True, verbose_name='Vencto.Lim.Créd.'),
        ),
    ]
