# Generated by Django 4.2.4 on 2023-08-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_global', '0006_alter_produtos_fornec_padrao_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='obs_prod',
            field=models.TextField(blank=True, db_comment='Observação do Produto', max_length=300, null=True, verbose_name='Obs. do Produto'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='vl_ult_compra_prod',
            field=models.DecimalField(blank=True, db_comment='Valor da Última Compra Produto', decimal_places=2, max_digits=8, null=True, verbose_name='Vl.Últ.Compra'),
        ),
    ]
