# Generated by Django 4.2.4 on 2023-08-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm_global', '0007_alter_produtos_obs_prod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='custo_std_prod',
            field=models.DecimalField(blank=True, db_comment='Custo Standad do Produto', decimal_places=2, max_digits=8, null=True, verbose_name='Custo Standad'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='prc_venda_prod',
            field=models.DecimalField(blank=True, db_comment='Preço de Venda do Produto', decimal_places=2, max_digits=8, null=True, verbose_name='Preço Venda'),
        ),
    ]
